### ISSUE TITLE
Support for Capacitor 5

### ISSUE THREAD

**Issue by hampusboas** [Fiksuruoka-fi/capacitor-klarna-kco#6]
Hi, First of all, thanks for this amazing plugin. Do you have any plans to add support for Capacitor 5?

Have a nice day.

**Comment by eljass** [comment]
Update is coming now, we needed it as well ;)

**Comment by hampusboas** [comment]
Wow, thank you. I'm more than happy to support your work. Do you have an paypal or pateron account so i can donate some money =) ?

**Comment by eljass** [comment]
@hampusboas thanks for thought but not really needed! We need this plugin as much as you do 😊 Happy if it works for others as well! Let us know if you find anything that does not work as expected!
