### ISSUE TITLE
net::ERR_BLOCKED_BY_RESPONSE

### ISSUE THREAD

**Issue by hampusboas** [Fiksuruoka-fi/capacitor-klarna-kco#8]
Hi, when i try to do a credit card purchase with the klarna integration i get net::ERR_BLOCKED_BY_RESPONSE.
Klarna tries to loads an external authorization to complete the purchase in my case from Nordea Bank. 

Have you seen this before and do you have a solution for this?

Many thanks in advance!

**Comment by hampusboas** [comment]
This is on android btw!

**Comment by hampusboas** [comment]
Same issue on ios also.

**Comment by hampusboas** [comment]
After severals hours of debugging it seems to be something with nordea and klarna. I tried another card from another bank and it worked like a charm!

**Comment by eljass** [comment]
Thanks for investigations, in our end we haven't heard feedback on Nordea's or other banks' cards to not work with this one so might also been temporary outage on Klarna's side.
